VNDK_SP_LIBRARIES := \
    android.hardware.graphics.common@1.0 \
	android.hardware.graphics.common@1.1 \
	android.hardware.graphics.common@1.2 \
	android.hardware.graphics.mapper@2.0 \
	android.hardware.graphics.mapper@2.1 \
	android.hardware.graphics.mapper@3.0 \
	ndroid.hardware.renderscript@1.0 \
	android.hidl.memory.token@1.0 \
	android.hidl.memory@1.0 \
	android.hidl.memory@1.0-impl \
	android.hidl.safe_union@1.0 \
	libRSCpuRef \
	libRSDriver \
	libRS_internal \
	libbacktrace \
	libbase \
	libbcinfo \
	libbinderthreadstate \
	libblas \
	libc++ \
	libcompiler_rt \
	libcutils \
	libhardware \
	libhidlbase \
	libhidlmemory \
	libhidltransport \
	libhwbinder \
	libhwbinder_noltopgo \
	libion \
	libjsoncpp \
	liblzma \
	libprocessgroup \
	libunwindstack \
	libutils \
	libutilscallstack \
	libz
